version: '3.4'

services:
  penguin:
    image: penguin
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8088:8088
    volumes: 
      - .:/usr/src/app
    links: 
      - mongodb

  mongodb:
    image: mongo:latest
    ports: 
      - 27017:27017
    volumes: 
      - data:/data/db

volumes: 
  data: 